Repository KSU-Google-DSC/Webapp, pull requests merged in 2022-08, with the labels that each got.

#30 Improve Error Page Design & Better Descriptive Errors
  src/pages/_error.js
Labels: Documentation, Feature, UI/UX, Overridden Review

#24 Implement Responsive Navbar (mobile) and Auto-rescaling Web Content
  src/components/DrawerComp.js
  src/components/navbar.js
  src/package-lock.json
  src/package.json
  src/pages/_app.js
  src/pages/about.js
  src/pages/index.js
  src/public/static/images/dsc-word.PNG
  src/public/static/images/wave.svg
  src/svg/anmwave.svg
Labels: Feature, UI/UX, Reviewing

#29 Support Firebase Configuration in Production Env File
  src/.env.production
Labels: Feature, Needs Review, Deployment, Security
