Repository KSU-Google-DSC/Webapp, pull requests merged in 2022-09, with the labels that each got.

#32 Bug Fixed (#31) Infinite Horizontal Wave
  src/components/navbar.js
  src/pages/index.js
  src/public/static/images/wave.svg
  src/public/static/images/wave1.svg
  src/public/static/images/wave2.svg
Labels: Bug Fix, Reviewing

#27 Implement Wave Animation to Landing Page
  src/components/navbar.js
  src/pages/index.js
  src/public/static/images/wave.svg
  src/public/static/images/wave1.svg
  src/public/static/images/wave2.svg
  src/public/static/images/wave_1.svg
  src/public/static/images/wave_2.svg
  src/public/static/images/wave_3.svg
  src/svg/dsclogo.svg
  src/svg/wave.svg
  src/svg/wavy.png
Labels: Feature, Needs Review, Dependencies, Blocked

#33 Implement About Page
  src/components/DrawerComp.js
  src/pages/about.js
  src/themes/theme.js
Labels: Feature, UI/UX, Review Approved

#34 Implement Event Page
  src/package-lock.json
  src/package.json
  src/pages/events.js
Labels: Feature, Dependencies, UI/UX, Review Approved

#35 Implement Team Page
  src/components/ProfileCard.js
  src/package-lock.json
  src/package.json
  src/pages/team.js
Labels: Feature, UI/UX, Review Approved

#39 Implement Recruitment Page
  src/components/navbar.js
  src/pages/opportunities.js
  src/public/static/images/oppo.png
  src/public/static/images/wave.svg
  src/themes/theme.js
Labels: Feature, UI/UX, Reviewing

#6 Implement Account Profiles, Google Provider Login, Authentication Tracking
  .gitignore
  Dockerfile
  README.md
  SECURITY.md
  src/.env.production
  src/next.config.js
  src/package-lock.json
  src/package.json
  src/pages/api/auth/[...nextauth].js
  src/public/static/images/wave_1.svg
  src/public/static/images/wave_2.svg
  src/public/static/images/wave_3.svg
  src/svg/anmwave.svg
  src/svg/dsclogo.svg
  src/svg/wave.svg
  src/svg/wavy.png
  src/temp_modules/FirebaseAdapter/converter.js
  src/temp_modules/FirebaseAdapter/index.js
Labels: Feature, Dependencies, Deployment, Security, Overridden Review

#25 Implement API endpoints for recruitment
  src/.env.production
  src/.gitignore
  src/components/navbar.js
  src/database.js
  src/package-lock.json
  src/package.json
  src/pages/api/applicants/[applicantKey]/delete.js
  src/pages/api/applicants/[applicantKey]/index.js
  src/pages/api/applicants/index.js
  src/pages/api/applicants/submit.js
  src/pages/api/auth/[...nextauth].js
  src/pages/api/hello.js
  src/temp_modules/FirebaseAdapter/converter.js
  src/temp_modules/FirebaseAdapter/index.js
Labels: Feature, Dependencies, Review Approved

#43 Updating Link in Homepage
  src/components/DrawerComp.js
  src/components/navbar.js
  src/pages/index.js
Labels: Feature, UI/UX, Review Approved
