Repository KSU-Google-DSC/Webapp, pull requests merged in 2022-11, with the labels that each got.

#57 Remove unauthenticated api/applicants/submit endpoint
  src/pages/api/applicants/submit.js
Labels: Feature, Security, Review Approved

#55 Fix Invalid Tab and Link components
  src/components/EventCardFlip.js
  src/components/navbar.js
  src/pages/about.js
Labels: Bug Fix, UI/UX, Review Approved

#61 Bugfix/fix aboutpage
  src/pages/about.js
  src/public/static/images/groupimage1.png
Labels: Bug Fix, UI/UX, Reviewing
