Repository KSU-Google-DSC/Webapp, pull requests merged in 2023-01, with the labels that each got.

#62 New Github Action to run Cypress Front end Tests
  .github/workflows/frontend_actions.yml
  .gitignore
  docs/automation/CYPRESS_README.md
  docs/automation/DOCKER_README.md
  docs/automation/GITHUB_ACTION_README.md
  src/components/navbar.js
  src/cypress.config.ts
  src/cypress/e2e/frontend_tests/frontend.nav_test.cy.js
  src/cypress/e2e/frontend_tests/frontend.screenshots.cy.js
  src/cypress/fixtures/pages.json
  src/cypress/prep_functions/page_fixture_creator.js
  src/package-lock.json
  src/package.json
Labels: Documentation, Feature, Dependencies, Deployment, Review Approved

#69 Fixed several errors that still shown in the console
  src/components/DrawerComp.js
  src/components/ProfileCard.js
  src/components/navbar.js
  src/pages/about.js
  src/pages/events.js
  src/pages/opportunities.js
  src/pages/socials.js
  src/pages/team.js
Labels: Bug Fix, Review Approved

#68 Convert all endpoints into a handler that calls an exported async function
  src/pages/api/applicants/[applicantKey]/index.js
  src/pages/api/applicants/index.js
  src/pages/api/applicants/submit.js
Labels: Feature, Security, Review Approved

#63 Implemented Login Page
  src/dashboard/dashboard.js
  src/pages/login.js
  src/public/static/images/loginbg.png
Labels: Feature, UI/UX, Reviewing

#44 Prod Nomination 0
  .dockerignore
  .github/workflows/frontend_actions.yml
  .github/workflows/gcr_deployment.yml
  .gitignore
  CONTRIBUTING.md
  Docker-compose.yml
  Dockerfile
  README.md
  SECURITY.md
  docs/automation/CYPRESS_README.md
  docs/automation/DOCKER_README.md
  docs/automation/GITHUB_ACTION_README.md
  scripts/build/build_dev.bat
  scripts/build/build_prod.bat
  scripts/clean/npm_cache.bat
  scripts/run/npm_run_dev.bat
  src/.env.production
  src/.eslintrc.json
  src/.gitignore
  src/.pre-commit-config.yaml
  src/components/DrawerComp.js
  src/components/EventCardFlip.js
  src/components/ProfileCard.js
  src/components/navbar.js
  src/cypress.config.ts
  src/cypress/e2e/frontend_tests/frontend.nav_test.cy.js
  src/cypress/e2e/frontend_tests/frontend.screenshots.cy.js
  src/cypress/fixtures/pages.json
  src/cypress/prep_functions/page_fixture_creator.js
  src/dashboard/dashboard.js
  src/database.js
  src/next.config.js
  src/package-lock.json
  src/package.json
  src/pages/_app.js
  src/pages/_error.js
  src/pages/about.js
  src/pages/api/applicants/[applicantKey]/delete.js
  src/pages/api/applicants/[applicantKey]/index.js
  src/pages/api/applicants/index.js
  src/pages/api/applicants/submit.js
  src/pages/api/auth/[...nextauth].js
  src/pages/api/events/all.js
  src/pages/api/hello.js
  src/pages/events.js
  src/pages/index.js
  src/pages/login.js
  src/pages/opportunities.js
  src/pages/socials.js
  src/pages/team.js
  src/public/static/images/dsc-word.PNG
  src/public/static/images/groupimage1.png
  src/public/static/images/loginbg.png
  src/public/static/images/oppo.png
  src/public/static/images/wave.svg
  src/public/static/images/wave1.svg
  src/public/static/images/wave2.svg
  src/themes/theme.js
Labels: Documentation, Feature, Bug Fix, Dependencies, Deployment, Security, UI/UX, Reviewing, Prod Nomination

#85 Updated eslintrc to have better rules
  .gitignore
  src/.eslintrc.json
  src/package-lock.json
  src/package.json
Labels: Feature, Reviewing, Github Actions, Best Practices

#84 OSSF Scorecard
  .github/workflows/security.yml
Labels: Security, Review Approved, Github Actions, Best Practices

#86 Updated next config with security goodies
  src/next.config.js
Labels: Feature, Security, Review Approved

#83 Add Dashboard & Default Authentication in Dev
  src/components/DashboardMenu.js
  src/components/DrawerComp.js
  src/components/Layout.js
  src/components/navbar.js
  src/package-lock.json
  src/package.json
  src/pages/_app.js
  src/pages/api/auth/[...nextauth].js
  src/pages/dashboard.js
  src/pages/dashboard/analytics.js
  src/pages/dashboard/applications.js
  src/pages/dashboard/events.js
  src/pages/dashboard/memberlist.js
  src/pages/dashboard/permission.js
  src/pages/login.js
  src/themes/theme.js
Labels: Feature, Security, UI/UX, Reviewing

#87 New Unit Test + Lint + Build Process
  .github/workflows/frontend_actions.yml
  .github/workflows/gcr_deployment.yml
  .github/workflows/integration.yml
  .github/workflows/security.yml
  src/.eslintrc.json
  src/cypress.config.js
  src/cypress.config.ts
  src/cypress/e2e/frontend_tests/frontend.dashboard_login.cy.js
  src/cypress/e2e/frontend_tests/frontend.nav_test.cy.js
  src/cypress/e2e/frontend_tests/frontend.screenshots.cy.js
  src/package.json
Labels: UI/UX, Review Approved, Github Actions, Unit Test
